version: 2
updates:
  - directory: /TransactionalOutBoxPattern/TransactionalOutBoxPattern.WebApi
    package-ecosystem: nuget
    schedule:
      interval: "daily"

  - directory: /TransactionalOutBoxPattern/TransactionalOutBoxPattern.Application
    package-ecosystem: nuget
    schedule:
      interval: "daily"

  - directory: /TransactionalOutBoxPattern/TransactionalOutBoxPattern.Infrastructure
    package-ecosystem: nuget
    schedule:
      interval: "daily"

  - directory: /TransactionalOutBoxPattern/TransactionalOutBoxPattern.Domain
    package-ecosystem: nuget
    schedule:
      interval: "daily"

  - directory: /TransactionalOutBoxPattern/TransactionalOutBoxPattern.WebApi
    package-ecosystem: docker
    schedule:
      interval: "daily"
